wandb_version: 1

K:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1663668829.194816
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.13
      5: 0.13.1
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 128
beta:
  desc: null
  value: 5
epochs:
  desc: null
  value: 200
hidden_dimension:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0001
